Algoritmo "semnome"
// 
//  
// Descrição   : Faça um algoritmo que receba o peso de uma pessoa em quilos, calcule e mostre esse peso
// em gramas.
// Autor(a)    : igor de jesus silva
// Data atual  : 12/3/2024
Var
// Seção de Declarações das variáveis 
pesokg, pesog: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite o pes em kilos")
leia(pesokg)
pesog <- pesokg * 1000
escreval("o seu peso em gramas é: ", pesog)

Fimalgoritmo