Algoritmo "semnome"
// 
//  
// Descrição   : Faça um algoritmo que calcule e mostre a área de um quadrado.
// Autor(a)    : igor de jesus silva
// Data atual  : 12/3/2024
Var
// Seção de Declarações das variáveis 
area, lado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite o lado do quadrado")
leia(lado)
area <- lado * lado
escreval("a area do quadrado é:", area )

Fimalgoritmo