algoritmo "semnome"
// Função :  Faça um algoritmo que calcule e mostre a área de um losango. Sabe-se que: A =
// (diagonal_maior * diagonal_menor)/2;
// Autor : igor de jesus silva
// Data : 12/03/2024
// Seção de Declarações 
var
dmaior, dmenor, area: real
inicio
escreval("digite a diagoanal maior")
leia(dmaior)
escreval("digite a diagonal menor")
leia(dmenor)
area <- (dmaior * dmenor)/2
escreval("a area do losango é: ", area)
// Seção de Comandos
fimalgoritmo
