algoritmo "Maior numero"
// Função : mostrar o maior numero
// Autor : Igor de Jesus Silva
// Data : 27/02/2024
// Seção de Declarações
var
num1, num2:real
inicio
escreval("Digite o primeiro numero:")
leia(num1)
escreval("Digite o segundo numero:")
leia(num2)
Se (num1>num2) entao
   escreval("O primeiro numero é maior")
   fimse
Se (num2>num1) entao
   escreval("O segundo numero é maior")
Fimse
Se (num1=num2) entao
     escreval("Os Numeros Sao iguais")
Fimse
fimalgoritmo
